# Gunakan base image Python resmi
FROM python:3.10-slim

# Set direktori kerja di dalam kontainer
WORKDIR /app

# Salin file requirements terlebih dahulu untuk caching layer
COPY requirements.txt ./

# Install dependensi Python
RUN pip install --no-cache-dir -r requirements.txt

# Salin sisa kode aplikasi ke direktori kerja
COPY . .

# Expose port yang digunakan oleh Streamlit
EXPOSE 8501

# Definisikan healthcheck untuk memonitor status aplikasi
HEALTHCHECK CMD streamlit hello --server.port=8501

# Perintah untuk menjalankan aplikasi saat kontainer dimulai
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.enableCORS=false"]